### ISSUE TITLE
Suggestions for importing SIM/Lattice-SIM images

### ISSUE THREAD

**Issue by clairemitchell308** [WeisongZhao/Sparse-SIM#10]
Hello,

Thank you very much for the cool software! 

I have a question about your recommendations for inputting SIM data into the software. As the original title was "Sparse-SIM" I anticipated that the software would also reconstruct from raw SIM data but I believe I can only input previously reconstructed SIM data. What method/software did you use to reconstruct your raw SIM data before running through Sparse-SIM please?

We have a Lattice-SIM system and we were very interested to run our generated data (reconstructed with Zeiss SIM/SIM^2 algorithm) through your algorithm, have you already tried this please?

**Comment by WeisongZhao** [comment]
Hi,

Yes, this software doesn't include a SIM reconstruction feature, and it is a deconvolution tool for a generel image enhancement. We reconstructed the raw SIM data using our custom-built software, but it is fully based on the `Gustafsson, M.G. et al. Three-dimensional resolution doubling in wide-field fluorescence microscopy by structured illumination. Biophys. J. 94, 4957–4970 (2008).`

Regarding the data from Zeiss SIM/SIM^2 algorithm, we haven't got a chance to try. But I'm happy to help and to see what will come out. Conceptually, I think the SIM^2 algorithm also includes an additional iterative-deconvolution as the last step (SIM + XXX deconvolution), which is already similar to our Sparse-SIM (SIM + Sparse deconvolution).

**Comment by clairemitchell308** [comment]
Thank you for the reply! So if I understand correctly we can try to use the Zeiss software (or other standard SIM reconstruction software) to reconstruct the SIM images (not SIM^2) and then run through Sparse-SIM. I wil try that out and let you know thank you!
