### ISSUE TITLE
Some confusion about sparse deconvolution

### ISSUE THREAD

**Issue by ZhenhongDu** [WeisongZhao/Sparse-SIM#2]
Dear Weisong
      Hello, I am very excited to tell you that sparse deconvolution has a very obvious processing effect on many kinds of microscope images. After reading your article and using sparse deconvolution, I still have some confusion. I sincerely hope to get your advice, thank you!
1. I found that the PSF estimation you used in Sparse-SIM GUI is two-dimensional form. When processing three-dimensional data (z-stack or time series), the procedure process the data slice by slice. For time series data, I think this is reasonable,  but for a three-dimensional stack (the z direction changes with depth), the psf should be three-dimensional. I have tried to change the iterative deconvolution part of your program to 3d RL, but I found that the one-by-one deconvolution you used is better, and I am a little confused.
2. For Sparse deconvolution, we first use sparse iteration to reduce the noise, and then perform RL deconvolution to get a significant improvement in resolution. I try to use the method of the article [Zhang, Zhe, Dongzhou Gou, Fan Feng, Ruyi Zheng, Ke Du, Hongrun Yang, Guangyi Zhang, et al. "3d Hessian Deconvolution of Thick Light-Sheet Z-Stacks for High-Contrast and High-Snr Volumetric Imaging." Photonics Research 8, no. 6 (2020): 1011-21.
](https://www.osapublishing.org/prj/fulltext.cfm?uri=prj-8-6-1011&id=432264) and add sparse restrictions. But its effect is not obvious. What is the reason for the worse resolution enhancement of one step deconvolution?It does include an iterative deblurring process. Are all the deconvolution methods inferior to RL, laugh and cry

**Comment by WeisongZhao** [comment]
Hi dzh

Thank you for your interests, and sorry for the delayed answer,

1. Yes, the reason I used the ‘2D deconvolution slice by slice’ is to maximize the lateral resolution enhancement. The 3D deconvolution indeed can further enhance the axial resolution, but the lateral resolution improvement might be limited. 

2. Actually, the two-step operation in this ‘Sparse deconvolution’ is one of the most crucial factors to maximize the effect of deconvolution. The reunion of the denoise and the deconvolution steps would lead to a performance regression.
