### ISSUE TITLE
Ask for specific setting instructions

### ISSUE THREAD

**Issue by lqffatbull** [WeisongZhao/Sparse-SIM#5]
Hello!

After carefully reading your masterpiece, I found this very useful software.

Excuse me, is there a specific setting guide for various parameters in this software? 

Thank you!

**Comment by WeisongZhao** [comment]
Hi, 
Thanks for your interests.
The detailed guide can be found in the [user manual](https://github.com/WeisongZhao/Sparse-SIM/blob/master/UserManual.pdf), [wiki](https://github.com/WeisongZhao/Sparse-SIM/wiki), and the [supplementary note 8](https://static-content.springer.com/esm/art%3A10.1038%2Fs41587-021-01092-2/MediaObjects/41587_2021_1092_MOESM1_ESM.pdf).
