### ISSUE TITLE
Software flash back problem

### ISSUE THREAD

**Issue by lqffatbull** [WeisongZhao/Sparse-SIM#6]
There was a software flash out today and I have reinstalled the software and still can't solve the problem.
Do you know how to address such a problem?

**Comment by WeisongZhao** [comment]
Hi,
Could you be more specific about this flash out issue? I haven't seen this type issue yet.
Did the software run properly the time before today?

**Comment by lqffatbull** [comment]
Sorry, it may be that I was too anxious for the first 2 days.
When the software was turned on, a short period of stuttering appeared, then it disappeared, and after approximately 5-10 s of waiting, it was presented with the final software interface.
It may be that this 5-10 s wait makes me mistake that the software collapses, reopens the software once, and goes into the dead cycle and...
This is good software, simple and easy to use with good results, thank you for your work!

**Comment by WeisongZhao** [comment]
Great! Glad to see it helps.
