### ISSUE TITLE
input data error (.tif) and how to export the reconstructed image?

### ISSUE THREAD

**Issue by sygongcode** [WeisongZhao/Sparse-SIM#7]
Hi, Weisong,

Thank you so much for sharing the excellent work. It was amazing!

Can I ask you two questions? First, how can I export the reconstructed image (where is the button on the GUI)？ 

And the second question: when I was using your software, I found I couldn't load my own data (TIF format and I got the image by using Zeiss 880 confocal microscopy). So, is there any special for the data or just a .tif format image is good?  Looking forward to your reply. Thank you.

Best regards,

Shangyu Gong

**Comment by WeisongZhao** [comment]
Hi Shangyu,

1. The image would be automatically saved in the folder `Data/SHReconstructed/ ****_**_**_**YourFileName_Video/YourFileName_reconstructed.tif`. The `****_**_**_**` is determined by the date you analyze the data. Could you have a check on your disk? The 'SHReconstructed' could be a good choice of key word for search.

2. Yes, a `.tif` (3 dimensions in maximum: `xy` or `xyt`/`xyz`) format input is fine. You can resave your raw data by ImageJ.

**Comment by sygongcode** [comment]
Hi, Weisong,

Thank you for your reply. I found the reconstructed files in the folder Data/SHReconstructed/. And I also resolved the data loading problem following your suggestion. I resaved my original data as 8-bit data by ImageJ, and then it works now. Thank you.

Best,

Shangyu
