### ISSUE TITLE
ovesampling?

### ISSUE THREAD

**Issue by GalaxyNight-day** [WeisongZhao/Sparse-SIM#8]
Hello there,

I have been recently found this algorithm and trying to use it for my research. 

I wonder how we can do the oversampling? I downloaded the software and whenever I choose "oversampling", it just doesn't do anything (the sparse reconstruction progress bar is 0%). 

Except for this, everything works fine. Would be very appreciated if you can help me out! 

Also, naive question. 

If I upsample the image, and use the correct pixel size for deconvolution, wouldn't that similar as "oversampling" option in the program?

Thanks!!!

**Comment by WeisongZhao** [comment]
Hi,

I'm glad you find this tool useful :).

Did you active the `GPU acceleration`, and did you use the binary version?

From user feedback, the binary version sometimes has to wait 10~20 mins for the `GPU acceleration`, but the script calling has no such issue (maybe you can have a try on this way?). I have no idea what happened during that time :), but I didn't come across this on my PCs. 

Regarding the pre-upsampling, yes, you can upsample the image before doing the `Sparse deconvolution` with the corresponding correct pixel size. 

Hope this would help.

**Comment by GalaxyNight-day** [comment]
Thanks for the prompt answer! I will try script calling. 

By the way, I was exploring your github and found SACD. It looks very interesting. Do you know when it will be on preprint?

**Comment by WeisongZhao** [comment]
Thanks for your interests!

The old version is at https://arxiv.org/abs/1809.07410, and the new version might be out soon in the next month, hopefully :).
