### ISSUE TITLE
PSF for confocal microsope?

### ISSUE THREAD

**Issue by GalaxyNight-day** [WeisongZhao/Sparse-SIM#9]
Hello there! 

I have been getting really good results compared to any other deconv method I have tried before including many of commercially available softwares, thank you very much for developing this :) 

Do you mind asking a question again?

Is there any code edit needed for PSF generation for the laser scanning confocal and/or laser spanning disk? I have been using default code for PSF generation, and I wonder if this is for widefield images?

**Comment by WeisongZhao** [comment]
Personal experience: there is no need for a confocal PSF generation (the results would have few differences). 

If your microscpope is a Airyscan-based confocal microscope, you can simply multiply the objective NA with a factor of 1.4 to generate the corresponding super-resolution confocal PSF.

In the original [manuscript](https://www.nature.com/articles/s41587-021-01092-2/figures/5) , we also apply deconvolution with this PSF on the SD-SIM (a confocal-based super-resolution microscope) and generate some fairly good results.
